steps:
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
- name: pwd
- name: hostname
- name: ll
